server:
  port: 8092
  
spring:
  datasource:
    name: storage
    url: jdbc:mysql://localhost:3306/wx?useSSL=false
    username: neptunium
    password: password
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update

endpoints:
  actuator:
    enabled: true
    sensitive: false
    
    
management:
  security:
    enabled: false

wx:
  log-command:
    - tail
    - "-F"
    - /var/log/syslog
#    - cat
#    - /home/neptunium/Documents/java/wx-log-viewer/src/main/resources/log